# solar-system pipeline
trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
 - job: Build_Solar_System
   displayName: "Build_Solar_System"
   steps:
    - template: _azure-pipelines/rust.yml
      parameters:
        toolchain: nightly
    - template: _azure-pipelines/geckodriver.yml
    - template: _azure-pipelines/wasm-pack.yml

    - script: |
        wasm-pack build --release --no-typescript
      displayName: 'Building WebAssembly'

    - script: |
        wasm-pack test --headless --firefox
      displayName: 'Testing WebAssembly'

    - script: |
        cd $(Build.SourcesDirectory)/www
        npm install
        npm run build
      displayName: 'Building Node App'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/www/dist'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/solar-system.zip'
        replaceExistingArchive: true 
    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'kurbaniec-release'
        repositoryName: 'kurbaniec-tgm/solar-system'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'gitTag'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'
        assets: '$(Build.ArtifactStagingDirectory)/*'